Repository Ravenbrook/mps, pull requests merged in 2023-03, with the labels that each got.

#149 Fix typos.
  code/eventdef.h
  code/freelist.c
  code/misc.h
  code/mpmtypes.h
  code/mpslib.h
  code/poolamc.c
  code/poollo.c
  code/root.c
  design/poolamc.txt
  tool/monitor
Labels: nice, low risk

#164 Fixing developer build on clang >=15
  code/amcss.c
  code/poolawl.c
  code/poollo.c
Labels: build, essential, low risk

#193 Tidy up design documentation for signatures
  code/abq.h
  code/arenacl.c
  code/arenavm.c
  code/arg.h
  code/boot.h
  code/dbgpool.h
  code/lockan.c
  code/lockix.c
  code/lockw3.c
  code/locus.h
  code/mpmst.h
  code/mpmtypes.h
  code/nailboard.h
  code/poolabs.c
  code/poolamc.c
  code/poolams.h
  code/poolawl.c
  code/poollo.c
  code/poolmrg.c
  code/poolmv2.c
  code/poolsnc.c
  code/prmcix.h
  code/prmcw3.h
  code/prmcxc.h
  code/protocol.h
  code/pthrdext.h
  code/root.c
  code/sa.h
  code/sac.h
  code/segsmss.c
  code/splay.h
  code/table.h
  code/than.c
  code/thix.c
  code/thw3.c
  code/thxc.c
  code/traceanc.c
  code/tract.h
  code/vm.h
  code/walk.c
  design/pool.txt
  design/sig.txt
Labels: documentation, optional, low risk, maintainability

#188 Unix: Use sysconf(_SC_PAGESIZE), not getpagesize()
  code/vmix.c
  design/vm.txt
Labels: os.xc, os.fr, optional, pending, low risk, os.li
