Repository Ravenbrook/mps, pull requests merged in 2023-01, with the labels that each got.

#92 Fix up array overrun warnings on gcc 11.3.0
  code/poolams.c
  code/poolmvff.c
Labels: build, essential

#91 Document the "m9" compiler toolchain.
  manual/source/topic/platform.rst
Labels: nice

#67 Update the MPS Manual for compatibility with Sphinx 3.
  design/abq.txt
  design/bt.txt
  design/buffer.txt
  design/clock.txt
  design/doc.txt
  design/fix.txt
  design/interface-c.txt
  design/locus.txt
  design/object-debug.txt
  design/prmc.txt
  design/ring.txt
  design/stack-scan.txt
  manual/Makefile
  manual/source/extensions/mps/__init__.py
  manual/source/extensions/mps/designs.py
  manual/source/guide/lang.rst
  manual/source/pool/ams.rst
  manual/source/pool/awl.rst
  manual/source/pool/lo.rst
  manual/source/pool/mvff.rst
  manual/source/pool/mvt.rst
  manual/source/topic/allocation.rst
  manual/source/topic/arena.rst
  manual/source/topic/cache.rst
  manual/source/topic/deprecated.rst
  manual/source/topic/format.rst
  manual/source/topic/interface.rst
  manual/source/topic/keyword.rst
  manual/source/topic/plinth.rst
  manual/source/topic/root.rst
  manual/source/topic/scanning.rst
Labels: documentation, build

#117 Check shell scripts during CI
  .github/workflows/shell-script-check.yml
  tool/check-shell-scripts
  tool/github-ci-kick
  tool/testcoverage
  tool/testemscripten
  tool/testopendylan
  tool/travis-ci-kick
Labels: nice

#97 Fix and update the pull request merge procedure
  .travis.yml
  contributing.rst
  procedure/pull-request-merge.rst
Labels: git-migration, process, essential
