Repository Ravenbrook/mps, pull requests merged in 2024-11, with the labels that each got.

#282 Fix typos.
  code/addrobj.c
  code/arena.c
  code/commpre.nmk
  code/dbgpool.c
  code/gcbench.c
  code/ld.c
  code/mpsi.c
  code/policy.c
  code/pool.c
  code/poolamc.c
  code/poolawl.c
  code/poolmrg.c
  code/shield.c
  code/splay.c
  code/tagtest.c
  code/trans.c
  design/finalize.txt
  design/freelist.txt
  design/io.txt
  design/message-gc.txt
  design/nailboard.txt
  design/object-debug.txt
  design/pool.txt
  design/poolams.txt
  design/poolmvt.txt
  design/prot.txt
  design/pthreadext.txt
  design/range.txt
  design/strategy.txt
  design/tests.txt
  design/write-barrier.txt
  manual/source/release.rst
  manual/source/topic/arena.rst
  manual/source/topic/cache.rst
  manual/source/topic/debugging.rst
  manual/source/topic/format.rst
  manual/source/topic/location.rst
  test/function/120.c
  test/function/235.c
  test/function/237.c
  test/function/43.c
  test/function/503.txt
  test/test/script/help/naming
  test/test/script/help/options
  test/test/script/help/output
  test/test/testlib/awlfmt.c
  test/test/testlib/preBQ.h
  test/test/testlib/testlib.c
  tool/monitor
Labels: low risk

#290 Fix link in readme to build docs.
  readme.txt
Labels: documentation, low risk

#297 Removing use of deprecated alias of VersionChange
  manual/source/extensions/mps/__init__.py
Labels: build, low risk
